### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'latitude'

### ISSUE THREAD

**Issue by FelixBuehler** [Ugluk4242/GEDCOM_MAPPING#3]
Hey,

I'm getting another error. I assume it's from some location which can't be geolocated?

```
Traceback (most recent call last):
  File "/mnt/c/Users/Felix/Desktop/GEDCOM_MAPPING/displacement_finder.py", line 193, in <module>
    dict_lat[d[4]] = location2.latitude
AttributeError: 'NoneType' object has no attribute 'latitude'
```

What's the best solution to solve this? Put it in a try error? Will that affect the overall video?

**Comment by Ugluk4242** [comment]
Check out city_modification, I use it to change the location names that do not work.Envoyé de mon iPhoneLe 17 juill. 2024 à 08:12, FelixBuehler ***@***.***> a écrit :﻿
Hey,
I'm getting another error. I assume it's from some location which can't be geolocated?
Traceback (most recent call last):
  File "/mnt/c/Users/Felix/Desktop/GEDCOM_MAPPING/displacement_finder.py", line 193, in <module>
    dict_lat[d[4]] = location2.latitude
AttributeError: 'NoneType' object has no attribute 'latitude'

What's the best solution to solve this? Put it in a try error? Will that affect the overall video?
